import { ColumnConfig } from "@/lib/Models/ColumnConfigModel";

export const IncidentAllColumnConfig: ColumnConfig[] = [
  {
    name: "Id",
    queryG: "number",
  },
  {
    name: "ActiveME",
    queryG: "active",
  },
  {
    name: "Activity",
    queryG: "activity",
  },
  {
    name: "ActivityDue",
    queryG: "activityDue",
  },
  {
    name: "ActualEnddate",
    queryG: "actualEnddate",
  },
  {
    name: "ActualStartDate",
    queryG: "actualStartDate",
  },
  {
    name: "AdditionalAssigneelist",
    queryG: "additionalAssigneelist",
  },
  {
    name: "AgileStory",
    queryG: "agileStory",
  },
  {
    name: "Approval",
    queryG: ` approval {
        name
      }`,
  },
  {
    name: "ApprovalHistory",
    queryG: `approvalHistory`,
  },
  {
    name: "ApprovalId",
    queryG: `approvalId`,
  },
  {
    name: "Approvalset",
    queryG: `approvalset`,
  },
  {
    name: "assignedTo",
    queryG: `assignedTo {
        name
      }`,
  },
  {
    name: "AssignmentGroup",
    queryG: `assignmentGroup {
        name
      }`,
  },
  {
    name: "BridgeStatus",
    queryG: `bridgeStatus`,
  },
  {
    name: "BusinessApplication",
    queryG: `businessApplication`,
  },
  {
    name: "BusinessDuration",
    queryG: `businessDuration`,
  },
  {
    name: "BusinessImpact",
    queryG: `businessImpact {
        name
      }`,
  },
  {
    name: "BusinessResolveTime",
    queryG: `businessresolvetime`,
  },
  {
    name: "BusinessUnit",
    queryG: `businessUnit`,
  },
  {
    name: "Caller",
    queryG: "caller{name id}",
  },
  {
    name: "CallerBu",
    queryG: `callerBu`,
  },
  {
    name: "CallerId",
    queryG: `callerId`,
  },
  {
    name: "CancelReason",
    queryG: `cancelReason`,
  },
  {
    name: "CausedByChange",
    queryG: `causedbyChange`,
  },
  {
    name: "Ceraised",
    queryG: `ceraised`,
  },
  {
    name: "ChangeRelated",
    queryG: `changeRelated`,
  },
  {
    name: "ChangeRequest",
    queryG: `changeRequest`,
  },
  {
    name: "ChildIncidents",
    queryG: `childIncidents`,
  },
  {
    name: "ClientName",
    queryG: `clientName`,
  },
  {
    name: "Closed",
    queryG: `closed`,
  },
  {
    name: "Closedby",
    queryG: `closedby {
        name
      }`,
  },
  {
    name: "ClosingCode",
    queryG: `closingCode {
        name
      }`,
  },
  { name: "Closenotes", queryG: `closenotes` },
  { name: "Company ", queryG: `company {name}` },
  { name: "ConfigurationItem ", queryG: `configurationItem {name}` },
  { name: "Contract", queryG: `contract` },
  { name: "CorrelationDisplay", queryG: `correlationDisplay` },
  { name: "CorrelationId", queryG: `correlationId` },
  { name: "Created", queryG: `created` },
  { name: "Createdby ", queryG: `createdby {name}` },
  { name: "DeliveryTask", queryG: `deliveryTask` },
  { name: "Description", queryG: `description` },
  { name: "Description1", queryG: `description1` },
  { name: "Domain", queryG: `domain` },
  { name: "DomainPath", queryG: `domainPath` },
  { name: "DueDate", queryG: `dueDate` },
  { name: "Duration", queryG: `duration` },
  { name: "Effectivenumber", queryG: `effectivenumber` },
  { name: "Emailflicker", queryG: `emailflicker` },
  { name: "EmailTemplate", queryG: `emailTemplate` },
  { name: "Escalation ", queryG: `escalation {status}` },
  { name: "Esignaturedocument", queryG: `esignaturedocument` },
  { name: "Esignaturetemplate", queryG: `esignaturetemplate` },
  { name: "Expectedstart", queryG: `expectedstart` },
  { name: "Findings", queryG: `findings` },
  { name: "Grouplist", queryG: `grouplist` },
  { name: "Gsdreassignmentcount", queryG: `gsdreassignmentcount` },
  { name: "Impact ", queryG: `impact {status}` },
  { name: "IncidentClassification", queryG: `incidentClassification` },
  { name: "Incidentstate ", queryG: `incidentstate {status}` },
  { name: "Initialimpactdetails", queryG: `initialimpactdetails` },
  { name: "Knowledge", queryG: `knowledge` },
  { name: "Knowledgearticle", queryG: `knowledgearticle` },
  { name: "KnownErrorArticle", queryG: `knownErrorArticle` },
  { name: "L1assigned", queryG: `l1assigned` },
  { name: "L1pending", queryG: `l1pending` },
  { name: "L1rest", queryG: `l1rest` },
  { name: "L2assigned", queryG: `l2assigned` },
  { name: "L2 pending", queryG: `l2pending` },
  { name: "L2 rest", queryG: `l2rest` },
  { name: "L3assigned", queryG: `l3assigned` },
  { name: "L3pending", queryG: `l3pending` },
  { name: "L3rest", queryG: `l3rest` },
  { name: "Lastreopenedat", queryG: `lastreopenedat` },
  { name: "Lastreopenedby ", queryG: `lastreopenedby {name}` },
  { name: "LastUpdated", queryG: `lastUpdated` },
  { name: "Location ", queryG: `location {name}` },
  { name: "Majorincidentstate", queryG: `majorincidentstate` },
  { name: "MonitoringStart", queryG: `monitoringStart` },
  { name: "Notify", queryG: `notify` },
  { name: "Onholdreason", queryG: `onholdreason` },
  { name: "Opened", queryG: `opened` },
  { name: "Openedby ", queryG: `openedby {name}` },
  { name: "OperationalTier1 ", queryG: `operationalTier1 {name}` },
  { name: "OperationalTier2 ", queryG: `operationalTier2 {name}` },
  { name: "Order", queryG: `order` },
  { name: "Origin", queryG: `origin` },
  { name: "Origintable", queryG: `origintable` },
  { name: "OtherAssigned", queryG: `otherAssigned` },
  { name: "OtherPending", queryG: `otherPending` },
  { name: "OtherRest", queryG: `otherRest` },
  { name: "Outageduration", queryG: `outageduration` },
  { name: "OutageEnd", queryG: `outageEnd` },
  { name: "OutageStart", queryG: `outageStart` },
  { name: "OutOfPolicy", queryG: `outOfPolicy` },
  { name: "OutOfPolicy1", queryG: `outOfPolicy1` },
  { name: "Overview", queryG: `overview` },
  { name: "Owner ", queryG: `owner {name}` },
  { name: "OwnerGroup ", queryG: `ownerGroup {name}` },
  { name: "Parent", queryG: `parent` },
  { name: "ParentIncident", queryG: `parentIncident` },
  { name: "Priority ", queryG: `priority {name}` },
  { name: "Probablecause", queryG: `probablecause` },
  { name: "Problem", queryG: `problem` },
  { name: "ProductTier1 ", queryG: `productTier1 {name}` },
  { name: "ProductTier2 ", queryG: `productTier2 {name}` },
  { name: "ProductTier3 ", queryG: `productTier3 {name}` },
  { name: "Promoted", queryG: `promoted` },
  { name: "Promotedby ", queryG: `promotedby {name}` },
  { name: "Proposed", queryG: `proposed` },
  { name: "ProposedbyId", queryG: `proposedbyId` },
  { name: "Reassignmentcount", queryG: `reassignmentcount` },
  { name: "Reopencount", queryG: `reopencount` },
  { name: "ReopenDate", queryG: `reopenDate` },
  { name: "Request", queryG: `request` },
  { name: "ResolutionOpsTier1 ", queryG: `resolutionOpsTier1 {name}` },
  { name: "ResolutionOpsTier2 ", queryG: `resolutionOpsTier2 {name}` },
  { name: "ResolutionProdTier1 ", queryG: `resolutionProdTier1 {name}` },
  { name: "ResolutionProdTier2 ", queryG: `resolutionProdTier2 {name}` },
  { name: "Resolved", queryG: `resolved` },
  { name: "Resolvedby ", queryG: `resolvedby {name}` },
  { name: "ResolvedbyTeam", queryG: `resolvedbyTeam` },
  { name: "Resolvetime", queryG: `resolvetime` },
  { name: "Routereason", queryG: `routereason` },
  { name: "Service", queryG: `service` },
  { name: "Serviceoffering", queryG: `serviceoffering` },
  { name: "ServiceTower ", queryG: `serviceTower {name}` },
  { name: "Severity ", queryG: `severity {name}` },
  { name: "Skills", queryG: `skills` },
  { name: "SlaassignmentGroup ", queryG: `slaassignmentGroup {name}` },
  { name: "Sladue ", queryG: `sladue {name}` },
  { name: "SpecifyCi", queryG: `specifyCi` },
  { name: "State ", queryG: `state {name}` },
  { name: "StrikeCount", queryG: `strikeCount` },
  { name: "StrikeCount1", queryG: `strikeCount1` },
  { name: "StrikeDate", queryG: `strikeDate` },
  { name: "StrikeDate1", queryG: `strikeDate1` },
  { name: "Subclosurecategory", queryG: `subclosurecategory` },
  { name: "Short description", queryG: "shortDescription" },
  { name: "Tags", queryG: `tags` },
  { name: "Tasktype", queryG: `tasktype` },
  { name: "TechnicalBridge", queryG: `technicalBridge` },
  { name: "Timeline", queryG: `timeline` },
  { name: "Timeworked", queryG: `timeworked` },
  { name: "TriggerRule", queryG: `triggerRule` },
  { name: "UniversalRequest", queryG: `universalRequest` },
  { name: "Updated", queryG: `updated` },
  { name: "UpdatedBy", queryG: `updatedBy` },
  { name: "UpdatedByNavigation ", queryG: `updatedByNavigation {name}` },
  { name: "Updates", queryG: `updates` },
  { name: "Uponapproval", queryG: `uponapproval` },
  { name: "Uponreject", queryG: `uponreject` },
  { name: "Urgency ", queryG: `urgency {status}` },
  { name: "Userinput", queryG: `userinput` },
  { name: "VendorCi", queryG: `vendorCi` },
  { name: "VendorContact", queryG: `vendorContact` },
  { name: "Vendorgroup ", queryG: `vendorgroup {status}` },
  { name: "VendorName", queryG: `vendorName` },
  { name: "VendorPriority ", queryG: `vendorPriority {status}` },
  { name: "VendorService", queryG: `vendorService` },
  { name: "VendorState ", queryG: `vendorState {status}` },
  { name: "Watchlist", queryG: `watchlist` },
  { name: "Worknoteslist", queryG: `worknoteslist` },
];
