import { EnumFilterConditionType } from "../../Models/FilterModels/FilterEnums";
import { FilterColumnValue } from "../../Models/FilterModels/FilterModels";
import { filterQueryTemplatePlaceholder } from "../commonData/QueryTemplet";

export const FilterColumnIncidentAll: FilterColumnValue[] = [
  {
    name: "Active",
    conditionType: EnumFilterConditionType.booleanType,
    inputValueType: EnumFilterConditionType.booleanType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `active: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Activity",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `activity: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "AdditionalAssigneelist",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `additionalAssigneelist: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "AgileStory",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `agileStory: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approval ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "approval ",
    tablePIdName: "id",
    query: `filterTable:approval {totalCount items {id name approvalType  inputValue:id}}`,
    filterQueryTemplate: `approvalId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Ceraised",
    conditionType: EnumFilterConditionType.booleanType,
    inputValueType: EnumFilterConditionType.booleanType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `ceraised: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ChangeRelated",
    conditionType: EnumFilterConditionType.booleanType,
    inputValueType: EnumFilterConditionType.booleanType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `changeRelated: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Emailflicker",
    conditionType: EnumFilterConditionType.booleanType,
    inputValueType: EnumFilterConditionType.booleanType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `emailflicker: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Fault",
    conditionType: EnumFilterConditionType.booleanType,
    inputValueType: EnumFilterConditionType.booleanType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `fault: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approval",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "approval",
    tablePIdName: "id",
    query: `filterTable:approval(where: { approvalType: { eq: 1 } }) { items { id name approvalType inputValue:id} }`,
    filterQueryTemplate: `approvalId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Assignedto ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "assignedTo ",
    tablePIdName: "id",
    query: `filterTable:assignedTo { items { id name inputValue:id} }`,
    filterQueryTemplate: `assignedToId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Assignmentgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "assignmentGroups",
    tablePIdName: "id",
    query: `filterTable:assignmentGroups(where: { groupType: { eq: 1 } }) { items { id name groupType inputValue:id} }`,
    filterQueryTemplate: `assignmentGroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Businessimpacts ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "businessImpacts ",
    tablePIdName: "id",
    query: `filterTable:businessImpacts { items { id name inputValue:id} }`,
    filterQueryTemplate: `businessImpactId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Callerusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "callerUsers ",
    tablePIdName: "id",
    query: `filterTable:callerUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `callerId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Channels ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "channels ",
    tablePIdName: "id",
    query: `filterTable:channels { items { id name inputValue:id} }`,
    filterQueryTemplate: `channelId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closedByUsers ",
    tablePIdName: "id",
    query: `filterTable:closedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `closedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closingcodes ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closingCodes ",
    tablePIdName: "id",
    query: `filterTable:closingCodes { items { id name inputValue:id} }`,
    filterQueryTemplate: `closingCodeId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Companies ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "companies ",
    tablePIdName: "id",
    query: `filterTable:companies { items { id name getnameofcompany inputValue:id} }`,
    filterQueryTemplate: `companieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Configurationitems",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "configurationItems",
    tablePIdName: "id",
    query: `filterTable:configurationItems(where: { configurationType: { eq: 1 } }) { items { id name configurationType inputValue:id} }`,
    filterQueryTemplate: `configurationItemId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Createdbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "createdByUsers ",
    tablePIdName: "id",
    query: `filterTable:createdByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `createdbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Escalations",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "escalations",
    tablePIdName: "id",
    query: `filterTable:escalations(where: { escalationType : { eq: 1 } }) { items { escalationType id status name:status inputValue:id} }`,
    filterQueryTemplate: `escalationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Impacts",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "impacts",
    tablePIdName: "id",
    query: `filterTable:impacts(where: { type : { eq: 1 } }) { items { id status type name:status inputValue:id} }`,
    filterQueryTemplate: `impactId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Incidentstates ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "incidentstates ",
    tablePIdName: "id",
    query: `filterTable:incidentstates { items { id status name:status inputValue:id} }`,
    filterQueryTemplate: `incidentstateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Lastreopenedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "lastreopenedByUsers ",
    tablePIdName: "id",
    query: `filterTable:lastreopenedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `lastreopenedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Locations ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "locations ",
    tablePIdName: "id",
    query: `filterTable:locations { items { id name inputValue:id} }`,
    filterQueryTemplate: `locationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Openedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "openedByUsers ",
    tablePIdName: "id",
    query: `filterTable:openedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `openedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Operationaltiers 1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "operationalTiers",
    tablePIdName: "id",
    query: `filterTable:operationalTiers(where: { typeofOperation : { eq: 1 } }) { items { id name typeofOperation inputValue:id} }`,
    filterQueryTemplate: `operationalTier1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Operationaltiers 2",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "operationalTiers",
    tablePIdName: "id",
    query: `filterTable:operationalTiers(where: { typeofOperation : { eq: 2 } }) { items { id name typeofOperation inputValue:id} }`,
    filterQueryTemplate: `operationalTier2Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Ownergroups ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "ownerGroups ",
    tablePIdName: "id",
    query: `filterTable:ownerGroups { items { id name inputValue:id} }`,
    filterQueryTemplate: `ownerGroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Ownerusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "ownerUsers ",
    tablePIdName: "id",
    query: `filterTable:ownerUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `ownerUserId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Priority",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "priority",
    tablePIdName: "id",
    query: `filterTable:priority(where: { type : { eq: 1 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `priorityId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Product tiers 1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "productTiers",
    tablePIdName: "id",
    query: `filterTable:productTiers(where: { type : { eq: 1 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `productTier1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Product tiers 2",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "productTiers",
    tablePIdName: "id",
    query: `filterTable:productTiers(where: { type : { eq: 2 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `productTier2Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Product tiers 3",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "productTiers",
    tablePIdName: "id",
    query: `filterTable:productTiers(where: { type : { eq: 3 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `productTier3Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Promotedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "promotedByUsers ",
    tablePIdName: "id",
    query: `filterTable:promotedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `promotedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Resolutionopstiers 1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "resolutionOpsTiers",
    tablePIdName: "id",
    query: `filterTable:resolutionOpsTiers(where: { type : { eq: 1 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `resolutionOpsTier1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Resolutionops tiers 2",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "resolutionOpsTiers",
    tablePIdName: "id",
    query: `filterTable:resolutionOpsTiers(where: { type : { eq: 2 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `resolutionOpsTier2Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Resolutionprodtiers 1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "resolutionProdTiers",
    tablePIdName: "id",
    query: `filterTable:resolutionProdTiers(where: { type : { eq: 1 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `resolutionProdTier1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Resolutionprodtiers 2",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "resolutionProdTiers",
    tablePIdName: "id",
    query: `filterTable:resolutionProdTiers(where: { type : { eq: 2 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `resolutionProdTier2Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Resolvedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "resolvedByUsers ",
    tablePIdName: "id",
    query: `filterTable:resolvedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `resolvedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Servicetowers",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "serviceTowers",
    tablePIdName: "id",
    query: `filterTable:serviceTowers(where: { serviceType : { eq: 1 } }) { items { id name serviceType inputValue:id} }`,
    filterQueryTemplate: `serviceTowerId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Severities ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "severities ",
    tablePIdName: "id",
    query: `filterTable:severities { items { id name inputValue:id} }`,
    filterQueryTemplate: `severitieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Slaassignmentgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "slaassignmentGroups",
    tablePIdName: "id",
    query: `filterTable:slaassignmentGroups(where: { groupType : { eq: 1 } }) { items { id name groupType inputValue:id} }`,
    filterQueryTemplate: `slaassignmentGroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Sladues ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "sladues ",
    tablePIdName: "id",
    query: `filterTable:sladues { items { id name inputValue:id} }`,
    filterQueryTemplate: `sladueId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "States",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "states",
    tablePIdName: "id",
    query: `filterTable:states(where: { type : { eq: 1 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `stateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Updatedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "updatedByUsers ",
    tablePIdName: "id",
    query: `filterTable:updatedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `updatedByUserId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Urgencies",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "urgencies",
    tablePIdName: "id",
    query: `filterTable:urgencies(where: { type : { eq: 1 } }) { items { id status name:status type inputValue:id} }`,
    filterQueryTemplate: `urgencieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorgroups",
    tablePIdName: "id",
    query: `filterTable:vendorgroups(where: { venderGroupType: { eq: 1 } }) { items { id status name:status venderGroupType inputValue:id} }`,
    filterQueryTemplate: `vendorgroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorpriorities",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorPriorities",
    tablePIdName: "id",
    query: `filterTable:vendorPriorities(where: { venderType : { eq: 1 } }) { items { id status name:status venderType inputValue:id} }`,
    filterQueryTemplate: `vendorPrioritieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorstates",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorStates",
    tablePIdName: "id",
    query: `filterTable:vendorStates(where: { venderStateType : { eq: 1 } }) { items { id status name:status venderStateType inputValue:id} }`,
    filterQueryTemplate: `vendorStateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "AdditionalAssigneelist",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `additionalAssigneelist: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "AgileStory",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `agileStory: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ApprovalHistory",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `approvalHistory: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approvalset",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `approvalset: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "BridgeStatus",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `bridgeStatus: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "BusinessApplication",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `businessApplication: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "BusinessUnit",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `businessUnit: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CancelReason",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `cancelReason: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CausedbyChange",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `causedbyChange: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ChangeRequest",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `changeRequest: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ClientName",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `clientName: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closenotes",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `closenotes: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Comments",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `comments: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CommentsandWorknotes",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `commentsandWorknotes: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CommentsWorknotes",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `commentsWorknotes: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Contract",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `contract: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CorrelationDisplay",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `correlationDisplay: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "CorrelationId",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `correlationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "DeliveryPlan",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `deliveryPlan: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "DeliveryTask",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `deliveryTask: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Description",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `description: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Description1",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `description1: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Domain",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `domain: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "DomainPath",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `domainPath: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Effectivenumber",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `effectivenumber: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "EmailTemplate",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `emailTemplate: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturedocument",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `esignaturedocument: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturetemplate",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `esignaturetemplate: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Expectedstart",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `expectedstart: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Findings",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `findings: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Followup",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `followup: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Grouplist",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `grouplist: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "IncidentClassification",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `incidentClassification: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Initialimpactdetails",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `initialimpactdetails: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Knowledgearticle",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `knowledgearticle: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "KnownErrorArticle",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `knownErrorArticle: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Majorincidentstate",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `majorincidentstate: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Notify",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `notify: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ID",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `number: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Onholdreason",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `onholdreason: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Order",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `order: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Origin",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `origin: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Origintable",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `origintable: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "OutOfPolicy",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `outOfPolicy: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "OutOfPolicy1",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `outOfPolicy1: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Overview",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `overview: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Parent",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `parent: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ParentIncident",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `parentIncident: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Probablecause",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `probablecause: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Problem",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `problem: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Promoted",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `promoted: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Proposed",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `proposed: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "RecordProducer",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `recordProducer: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Request",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `request: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ResolvedbyTeam",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `resolvedbyTeam: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Routereason",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `routereason: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Service",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `service: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Serviceoffering",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `serviceoffering: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "ShortDescription",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `shortDescription: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Skills",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `skills: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "SpecifyCi",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `specifyCi: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Subclosurecategory",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `subclosurecategory: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Tags",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `tags: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Tasktype",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `tasktype: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "TechnicalBridge",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `technicalBridge: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Timeline",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `timeline: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "TriggerRule",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `triggerRule: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "UniversalRequest",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `universalRequest: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Uponapproval",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `uponapproval: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Uponreject",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `uponreject: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Userinput",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `userinput: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "VendorCi",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `vendorCi: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "VendorContact",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `vendorContact: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "VendorName",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `vendorName: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "VendorService",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `vendorService: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Watchlist",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `watchlist: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Worknotes",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `worknotes: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Worknoteslist",
    conditionType: EnumFilterConditionType.stringType,
    inputValueType: EnumFilterConditionType.stringType,
    inputDataFetchQuery: "",
    tableName: "",
    tablePIdName: "",
    query: "",
    filterQueryTemplate: `worknoteslist: { ${filterQueryTemplatePlaceholder} }`,
  },
];
