import { EnumFilterConditionType } from "@/lib/Models/FilterModels/FilterEnums";
import { FilterColumnValue } from "@/lib/Models/FilterModels/FilterModels";
import { filterQueryTemplatePlaceholder } from "../commonData/QueryTemplet";

export const FilterColumnRequestAll: FilterColumnValue[] = [
  {
    name: "Additionalassigneelists ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "additionalassigneelists ",
    tablePIdName: "id",
    query: `filterTable:additionalassigneelists { items { id name inputValue:id} }`,
    filterQueryTemplate: `additionalassigneelistId:  { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approval",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "approval",
    tablePIdName: "id",
    query: `filterTable:approval(where: { approvalType: { eq: 2 } }) { items { id name approvalType inputValue:id} }`,
    filterQueryTemplate: `approvalId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Assignedto ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "assignedTo ",
    tablePIdName: "id",
    query: `filterTable:assignedTo { items { id name inputValue:id} }`,
    filterQueryTemplate: `assignedToId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Assignmentgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "assignmentGroups",
    tablePIdName: "id",
    query: `filterTable:assignmentGroups(where: { groupType: { eq: 2 } }) { items { id name groupType inputValue:id} }`,
    filterQueryTemplate: `assignmentGroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Businessunit ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "businessUnit ",
    tablePIdName: "id",
    query: `filterTable:businessUnit { items { id name inputValue:id} } `,
    filterQueryTemplate: `businessUnitId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closeddeliveredbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closedDeliveredByUsers ",
    tablePIdName: "id",
    query: `filterTable:closedDeliveredByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `closedDeliveredById: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Configurationitems",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "configurationItems",
    tablePIdName: "id",
    query: `filterTable:configurationItems(where: { configurationType: { eq: 2 } }) { items { id name configurationType inputValue:id} }`,
    filterQueryTemplate: `configurationItemId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Contacttypes ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "contactTypes ",
    tablePIdName: "id",
    query: `filterTable:contactTypes { items { id name contactType1 inputValue:id} }`,
    filterQueryTemplate: `contactTypeId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Deliveryplans ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "deliveryPlans ",
    tablePIdName: "id",
    query: `filterTable:deliveryPlans { items { id name inputValue:id} }`,
    filterQueryTemplate: `deliveryPlanId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Domains ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "domains ",
    tablePIdName: "id",
    query: `filterTable:domains { items { id name inputValue:id} }`,
    filterQueryTemplate: `domainId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Escalations",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "escalations",
    tablePIdName: "id",
    query: `filterTable:escalations(where: { escalationType : { eq: 2 } }) { items { escalationType id status name:status inputValue:id} }`,
    filterQueryTemplate: `escalationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Impacts",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "impacts",
    tablePIdName: "id",
    query: `filterTable:impacts(where: { type : { eq: 2 } }) { items { id status type name:status inputValue:id} }`,
    filterQueryTemplate: `impactId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Requestitems",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "requestItems",
    tablePIdName: "id",
    query: `filterTable:requestItems(where: { itemType : { eq: 2 } }) { items { id itemType name inputValue:id} }`,
    filterQueryTemplate: `itemId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Locations ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "locations ",
    tablePIdName: "id",
    query: `filterTable:locations { items { id name inputValue:id} }`,
    filterQueryTemplate: `locationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Openedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "openedByUsers ",
    tablePIdName: "id",
    query: `filterTable:openedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `openedById: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Orderguides ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "orderGuides ",
    tablePIdName: "id",
    query: `filterTable:orderGuides { items { id name inputValue:id} }`,
    filterQueryTemplate: `orderGuideId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Ownergroups ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "ownerGroups ",
    tablePIdName: "id",
    query: `filterTable:ownerGroups { items { id name inputValue:id} }`,
    filterQueryTemplate: `ownerGroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Ownerusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "ownerUsers ",
    tablePIdName: "id",
    query: `filterTable:ownerUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `ownerId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Requestedforusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "requestedForUsers ",
    tablePIdName: "id",
    query: `filterTable:requestedForUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `requestedForId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Priority",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "priority",
    tablePIdName: "id",
    query: `filterTable:priority(where: { type : { eq: 2 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `priorityId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Requeststates",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "requestStates",
    tablePIdName: "id",
    query: `filterTable:requestStates(where: { stateType : { eq: 2 } }) { items { id name stateType inputValue:id} }`,
    filterQueryTemplate: `requestStateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Services ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "services ",
    tablePIdName: "id",
    query: `filterTable:services { items { id name inputValue:id} }`,
    filterQueryTemplate: `serviceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Servicetowers",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "serviceTowers",
    tablePIdName: "id",
    query: `filterTable:serviceTowers(where: { serviceType : { eq: 2 } }) { items { id name serviceType inputValue:id} }`,
    filterQueryTemplate: `serviceTowerId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Slaassignmentgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "slaassignmentGroups",
    tablePIdName: "id",
    query: `filterTable:slaassignmentGroups(where: { groupType : { eq: 2 } }) { items { id name groupType inputValue:id} }`,
    filterQueryTemplate: `slaAssignmentGroupsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Sladues ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "sladues ",
    tablePIdName: "id",
    query: `filterTable:sladues { items { id name inputValue:id} }`,
    filterQueryTemplate: `sladueId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Stages ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "stages ",
    tablePIdName: "id",
    query: `filterTable:stages { items { id name inputValue:id} }`,
    filterQueryTemplate: `stageId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "States",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "states",
    tablePIdName: "id",
    query: `filterTable:states(where: { type : { eq: 2 } }) { items { id name type inputValue:id} }`,
    filterQueryTemplate: `stateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Tasktypes ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "tasktypes ",
    tablePIdName: "id",
    query: `filterTable:tasktypes { items { id name inputValue:id} }`,
    filterQueryTemplate: `tasktypeId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Updatedbyusers ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "updatedByUsers ",
    tablePIdName: "id",
    query: `filterTable:updatedByUsers { items { id name inputValue:id} }`,
    filterQueryTemplate: `updatedByUserId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Uponapprovals ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "uponApprovals ",
    tablePIdName: "id",
    query: `filterTable:uponApprovals { items { id name inputValue:id} }`,
    filterQueryTemplate: `uponApprovalId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Uponrejects ",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "uponRejects ",
    tablePIdName: "id",
    query: `filterTable:uponRejects { items { id name inputValue:id} }`,
    filterQueryTemplate: `uponRejectId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Urgencies",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "urgencies",
    tablePIdName: "id",
    query: `filterTable:urgencies(where: { type : { eq: 2 } }) { items { id status name:status type inputValue:id} }`,
    filterQueryTemplate: `urgencieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorgroups",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorgroups",
    tablePIdName: "id",
    query: `filterTable:vendorgroups(where: { venderGroupType: { eq: 2 } }) { items { id status name:status venderGroupType inputValue:id} }`,
    filterQueryTemplate: `vendorgroupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorpriorities",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorPriorities",
    tablePIdName: "id",
    query: `filterTable:vendorPriorities(where: { venderType : { eq: 2 } }) { items { id status name:status venderType inputValue:id} }`,
    filterQueryTemplate: `vendorPrioritieId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorstates",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorStates",
    tablePIdName: "id",
    query: `filterTable:vendorStates(where: { venderStateType : { eq: 2 } }) { items { id status name:status venderStateType inputValue:id} }`,
    filterQueryTemplate: `vendorStateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Activity",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "activity",
    tablePIdName: "id",
    query: `filterTable:activity`,
    filterQueryTemplate: `activityId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Activitydue",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "activitydue",
    tablePIdName: "id",
    query: `filterTable:activitydue`,
    filterQueryTemplate: `activitydueId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Agilestory",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "agilestory",
    tablePIdName: "id",
    query: `filterTable:agilestory`,
    filterQueryTemplate: `agilestoryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approvalhistory",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "approvalhistory",
    tablePIdName: "id",
    query: `filterTable:approvalhistory`,
    filterQueryTemplate: `approvalhistoryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Businessapplication",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "businessapplication",
    tablePIdName: "id",
    query: `filterTable:businessapplication`,
    filterQueryTemplate: `businessapplicationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Catalog",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "catalog",
    tablePIdName: "id",
    query: `filterTable:catalog`,
    filterQueryTemplate: `catalogId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closedby",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closedby",
    tablePIdName: "id",
    query: `filterTable:closedby`,
    filterQueryTemplate: `closedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closenotes",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closeNotes",
    tablePIdName: "id",
    query: `filterTable:closeNotes`,
    filterQueryTemplate: `closeNotesId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Column1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "column1",
    tablePIdName: "id",
    query: `filterTable:column1`,
    filterQueryTemplate: `column1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Comments",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "comments",
    tablePIdName: "id",
    query: `filterTable:comments`,
    filterQueryTemplate: `commentsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Commentsandworknotes",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "commentsAndWorkNotes",
    tablePIdName: "id",
    query: `filterTable:commentsAndWorkNotes`,
    filterQueryTemplate: `commentsAndWorkNotesId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Context",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "context",
    tablePIdName: "id",
    query: `filterTable:context`,
    filterQueryTemplate: `contextId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Contract",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "contract",
    tablePIdName: "id",
    query: `filterTable:contract`,
    filterQueryTemplate: `contractId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Correlationid",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "correlationId",
    tablePIdName: "id",
    query: `filterTable:correlationId`,
    filterQueryTemplate: `correlationIdId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Correlationdisplay",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "correlationdisplay",
    tablePIdName: "id",
    query: `filterTable:correlationdisplay`,
    filterQueryTemplate: `correlationdisplayId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Crid",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "crId",
    tablePIdName: "id",
    query: `filterTable:crId`,
    filterQueryTemplate: `crIdId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Createdby",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "createdby",
    tablePIdName: "id",
    query: `filterTable:createdby`,
    filterQueryTemplate: `createdbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Damcorequestnumber",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "damcoRequestNumber",
    tablePIdName: "id",
    query: `filterTable:damcoRequestNumber`,
    filterQueryTemplate: `damcoRequestNumberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Deliverytask",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "deliverytask",
    tablePIdName: "id",
    query: `filterTable:deliverytask`,
    filterQueryTemplate: `deliverytaskId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Description",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "description",
    tablePIdName: "id",
    query: `filterTable:description`,
    filterQueryTemplate: `descriptionId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Domainpath",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "domainPath",
    tablePIdName: "id",
    query: `filterTable:domainPath`,
    filterQueryTemplate: `domainPathId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Effectivenumber",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "effectivenumber",
    tablePIdName: "id",
    query: `filterTable:effectivenumber`,
    filterQueryTemplate: `effectivenumberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Emailtemplate",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "emailTemplate",
    tablePIdName: "id",
    query: `filterTable:emailTemplate`,
    filterQueryTemplate: `emailTemplateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturedocument",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "esignaturedocument",
    tablePIdName: "id",
    query: `filterTable:esignaturedocument`,
    filterQueryTemplate: `esignaturedocumentId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturetemplate",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "esignaturetemplate",
    tablePIdName: "id",
    query: `filterTable:esignaturetemplate`,
    filterQueryTemplate: `esignaturetemplateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Estimateddelivery",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "estimatedDelivery",
    tablePIdName: "id",
    query: `filterTable:estimatedDelivery`,
    filterQueryTemplate: `estimatedDeliveryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Fault",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "fault",
    tablePIdName: "id",
    query: `filterTable:fault`,
    filterQueryTemplate: `faultId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Flowcontext",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "flowContext",
    tablePIdName: "id",
    query: `filterTable:flowContext`,
    filterQueryTemplate: `flowContextId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Followup",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "followup",
    tablePIdName: "id",
    query: `filterTable:followup`,
    filterQueryTemplate: `followupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Grouplist",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "grouplist",
    tablePIdName: "id",
    query: `filterTable:grouplist`,
    filterQueryTemplate: `grouplistId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Madesla",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "madeSla",
    tablePIdName: "id",
    query: `filterTable:madeSla`,
    filterQueryTemplate: `madeSlaId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Number",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "number",
    tablePIdName: "id",
    query: `filterTable:number`,
    filterQueryTemplate: `numberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Orderr",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "orderr",
    tablePIdName: "id",
    query: `filterTable:orderr`,
    filterQueryTemplate: `orderrId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Outofpolicy",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "outOfPolicy",
    tablePIdName: "id",
    query: `filterTable:outOfPolicy`,
    filterQueryTemplate: `outOfPolicyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Parent",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "parent",
    tablePIdName: "id",
    query: `filterTable:parent`,
    filterQueryTemplate: `parentId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Price",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "price",
    tablePIdName: "id",
    query: `filterTable:price`,
    filterQueryTemplate: `priceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Recurringprice",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "recurringPrice",
    tablePIdName: "id",
    query: `filterTable:recurringPrice`,
    filterQueryTemplate: `recurringPriceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Recurringpricefrequency",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "recurringPriceFrequency",
    tablePIdName: "id",
    query: `filterTable:recurringPriceFrequency`,
    filterQueryTemplate: `recurringPriceFrequencyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Requestids",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "requestIds",
    tablePIdName: "id",
    query: `filterTable:requestIds`,
    filterQueryTemplate: `requestIdsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Routereason",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "routereason",
    tablePIdName: "id",
    query: `filterTable:routereason`,
    filterQueryTemplate: `routereasonId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Serviceoffering",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "serviceoffering",
    tablePIdName: "id",
    query: `filterTable:serviceoffering`,
    filterQueryTemplate: `serviceofferingId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Shortdescription",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "shortDescription",
    tablePIdName: "id",
    query: `filterTable:shortDescription`,
    filterQueryTemplate: `shortDescriptionId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Skills",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "skills",
    tablePIdName: "id",
    query: `filterTable:skills`,
    filterQueryTemplate: `skillsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Specialinstructions",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "specialInstructions",
    tablePIdName: "id",
    query: `filterTable:specialInstructions`,
    filterQueryTemplate: `specialInstructionsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Specifyci",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "specifyCi",
    tablePIdName: "id",
    query: `filterTable:specifyCi`,
    filterQueryTemplate: `specifyCiId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Tags",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "tags",
    tablePIdName: "id",
    query: `filterTable:tags`,
    filterQueryTemplate: `tagsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Universalrequest",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "universalRequest",
    tablePIdName: "id",
    query: `filterTable:universalRequest`,
    filterQueryTemplate: `universalRequestId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Userinput",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "userinput",
    tablePIdName: "id",
    query: `filterTable:userinput`,
    filterQueryTemplate: `userinputId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorci",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorCi",
    tablePIdName: "id",
    query: `filterTable:vendorCi`,
    filterQueryTemplate: `vendorCiId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorcontact",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorContact",
    tablePIdName: "id",
    query: `filterTable:vendorContact`,
    filterQueryTemplate: `vendorContactId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorname",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorName",
    tablePIdName: "id",
    query: `filterTable:vendorName`,
    filterQueryTemplate: `vendorNameId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorservice",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorService",
    tablePIdName: "id",
    query: `filterTable:vendorService`,
    filterQueryTemplate: `vendorServiceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Watchlist",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "watchlist",
    tablePIdName: "id",
    query: `filterTable:watchlist`,
    filterQueryTemplate: `watchlistId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Activity",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "activity",
    tablePIdName: "id",
    query: `filterTable:activity`,
    filterQueryTemplate: `activityId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Activitydue",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "activitydue",
    tablePIdName: "id",
    query: `filterTable:activitydue`,
    filterQueryTemplate: `activitydueId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Agilestory",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "agilestory",
    tablePIdName: "id",
    query: `filterTable:agilestory`,
    filterQueryTemplate: `agilestoryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Approvalhistory",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "approvalhistory",
    tablePIdName: "id",
    query: `filterTable:approvalhistory`,
    filterQueryTemplate: `approvalhistoryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Businessapplication",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "businessapplication",
    tablePIdName: "id",
    query: `filterTable:businessapplication`,
    filterQueryTemplate: `businessapplicationId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Catalog",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "catalog",
    tablePIdName: "id",
    query: `filterTable:catalog`,
    filterQueryTemplate: `catalogId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closedby",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closedby",
    tablePIdName: "id",
    query: `filterTable:closedby`,
    filterQueryTemplate: `closedbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Closenotes",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "closeNotes",
    tablePIdName: "id",
    query: `filterTable:closeNotes`,
    filterQueryTemplate: `closeNotesId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Column1",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "column1",
    tablePIdName: "id",
    query: `filterTable:column1`,
    filterQueryTemplate: `column1Id: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Comments",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "comments",
    tablePIdName: "id",
    query: `filterTable:comments`,
    filterQueryTemplate: `commentsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Commentsandworknotes",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "commentsAndWorkNotes",
    tablePIdName: "id",
    query: `filterTable:commentsAndWorkNotes`,
    filterQueryTemplate: `commentsAndWorkNotesId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Context",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "context",
    tablePIdName: "id",
    query: `filterTable:context`,
    filterQueryTemplate: `contextId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Contract",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "contract",
    tablePIdName: "id",
    query: `filterTable:contract`,
    filterQueryTemplate: `contractId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Correlationid",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "correlationId",
    tablePIdName: "id",
    query: `filterTable:correlationId`,
    filterQueryTemplate: `correlationIdId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Correlationdisplay",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "correlationdisplay",
    tablePIdName: "id",
    query: `filterTable:correlationdisplay`,
    filterQueryTemplate: `correlationdisplayId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Crid",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "crId",
    tablePIdName: "id",
    query: `filterTable:crId`,
    filterQueryTemplate: `crIdId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Createdby",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "createdby",
    tablePIdName: "id",
    query: `filterTable:createdby`,
    filterQueryTemplate: `createdbyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Damcorequestnumber",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "damcoRequestNumber",
    tablePIdName: "id",
    query: `filterTable:damcoRequestNumber`,
    filterQueryTemplate: `damcoRequestNumberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Deliverytask",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "deliverytask",
    tablePIdName: "id",
    query: `filterTable:deliverytask`,
    filterQueryTemplate: `deliverytaskId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Description",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "description",
    tablePIdName: "id",
    query: `filterTable:description`,
    filterQueryTemplate: `descriptionId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Domainpath",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "domainPath",
    tablePIdName: "id",
    query: `filterTable:domainPath`,
    filterQueryTemplate: `domainPathId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Effectivenumber",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "effectivenumber",
    tablePIdName: "id",
    query: `filterTable:effectivenumber`,
    filterQueryTemplate: `effectivenumberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Emailtemplate",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "emailTemplate",
    tablePIdName: "id",
    query: `filterTable:emailTemplate`,
    filterQueryTemplate: `emailTemplateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturedocument",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "esignaturedocument",
    tablePIdName: "id",
    query: `filterTable:esignaturedocument`,
    filterQueryTemplate: `esignaturedocumentId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Esignaturetemplate",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "esignaturetemplate",
    tablePIdName: "id",
    query: `filterTable:esignaturetemplate`,
    filterQueryTemplate: `esignaturetemplateId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Estimateddelivery",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "estimatedDelivery",
    tablePIdName: "id",
    query: `filterTable:estimatedDelivery`,
    filterQueryTemplate: `estimatedDeliveryId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Fault",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "fault",
    tablePIdName: "id",
    query: `filterTable:fault`,
    filterQueryTemplate: `faultId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Flowcontext",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "flowContext",
    tablePIdName: "id",
    query: `filterTable:flowContext`,
    filterQueryTemplate: `flowContextId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Followup",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "followup",
    tablePIdName: "id",
    query: `filterTable:followup`,
    filterQueryTemplate: `followupId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Grouplist",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "grouplist",
    tablePIdName: "id",
    query: `filterTable:grouplist`,
    filterQueryTemplate: `grouplistId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Madesla",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "madeSla",
    tablePIdName: "id",
    query: `filterTable:madeSla`,
    filterQueryTemplate: `madeSlaId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Number",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "number",
    tablePIdName: "id",
    query: `filterTable:number`,
    filterQueryTemplate: `numberId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Orderr",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "orderr",
    tablePIdName: "id",
    query: `filterTable:orderr`,
    filterQueryTemplate: `orderrId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Outofpolicy",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "outOfPolicy",
    tablePIdName: "id",
    query: `filterTable:outOfPolicy`,
    filterQueryTemplate: `outOfPolicyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Parent",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "parent",
    tablePIdName: "id",
    query: `filterTable:parent`,
    filterQueryTemplate: `parentId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Price",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "price",
    tablePIdName: "id",
    query: `filterTable:price`,
    filterQueryTemplate: `priceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Recurringprice",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "recurringPrice",
    tablePIdName: "id",
    query: `filterTable:recurringPrice`,
    filterQueryTemplate: `recurringPriceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Recurringpricefrequency",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "recurringPriceFrequency",
    tablePIdName: "id",
    query: `filterTable:recurringPriceFrequency`,
    filterQueryTemplate: `recurringPriceFrequencyId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Requestids",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "requestIds",
    tablePIdName: "id",
    query: `filterTable:requestIds`,
    filterQueryTemplate: `requestIdsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Routereason",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "routereason",
    tablePIdName: "id",
    query: `filterTable:routereason`,
    filterQueryTemplate: `routereasonId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Serviceoffering",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "serviceoffering",
    tablePIdName: "id",
    query: `filterTable:serviceoffering`,
    filterQueryTemplate: `serviceofferingId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Shortdescription",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "shortDescription",
    tablePIdName: "id",
    query: `filterTable:shortDescription`,
    filterQueryTemplate: `shortDescriptionId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Skills",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "skills",
    tablePIdName: "id",
    query: `filterTable:skills`,
    filterQueryTemplate: `skillsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Specialinstructions",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "specialInstructions",
    tablePIdName: "id",
    query: `filterTable:specialInstructions`,
    filterQueryTemplate: `specialInstructionsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Specifyci",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "specifyCi",
    tablePIdName: "id",
    query: `filterTable:specifyCi`,
    filterQueryTemplate: `specifyCiId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Tags",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "tags",
    tablePIdName: "id",
    query: `filterTable:tags`,
    filterQueryTemplate: `tagsId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Universalrequest",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "universalRequest",
    tablePIdName: "id",
    query: `filterTable:universalRequest`,
    filterQueryTemplate: `universalRequestId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Userinput",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "userinput",
    tablePIdName: "id",
    query: `filterTable:userinput`,
    filterQueryTemplate: `userinputId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorci",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorCi",
    tablePIdName: "id",
    query: `filterTable:vendorCi`,
    filterQueryTemplate: `vendorCiId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorcontact",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorContact",
    tablePIdName: "id",
    query: `filterTable:vendorContact`,
    filterQueryTemplate: `vendorContactId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorname",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorName",
    tablePIdName: "id",
    query: `filterTable:vendorName`,
    filterQueryTemplate: `vendorNameId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Vendorservice",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "vendorService",
    tablePIdName: "id",
    query: `filterTable:vendorService`,
    filterQueryTemplate: `vendorServiceId: { ${filterQueryTemplatePlaceholder} }`,
  },
  {
    name: "Watchlist",
    conditionType: EnumFilterConditionType.dataFetchType,
    inputValueType: EnumFilterConditionType.dataFetchType,
    inputDataFetchQuery: "",
    tableName: "watchlist",
    tablePIdName: "id",
    query: `filterTable:watchlist`,
    filterQueryTemplate: `watchlistId: { ${filterQueryTemplatePlaceholder} }`,
  },
];
