import { ColumnConfig } from "@/lib/Models/ColumnConfigModel";

export const RequestAllColumnConfig: ColumnConfig[] = [
  { name: "Active", queryG: `active` },
  { name: "Activity", queryG: `activity` },
  { name: "Activitydue", queryG: `activitydue` },
  { name: "Actualenddate", queryG: `actualenddate` },
  { name: "Actualstartdate", queryG: `actualstartdate` },
  { name: "Additionalassigneelist ", queryG: `additionalassigneelist {name}` },
  { name: "AdditionalassigneelistId", queryG: `additionalassigneelistId` },
  { name: "Agilestory", queryG: `agilestory` },
  { name: "Approval ", queryG: `approval {name}` },
  { name: "Approvalhistory", queryG: `approvalhistory` },
  { name: "ApprovalId", queryG: `approvalId` },
  { name: "Approvalset", queryG: `approvalset` },
  { name: "AssignedTo ", queryG: `assignedTo {name}` },
  { name: "AssignmentGroup ", queryG: `assignmentGroup {name}` },
  { name: "Businessapplication", queryG: `businessapplication` },
  { name: "Businessduration", queryG: `businessduration` },
  { name: "BusinessUnit ", queryG: `businessUnit {name}` },
  { name: "Closed", queryG: `closed` },
  { name: "Closedby", queryG: `closedby` },
  { name: "Comments", queryG: `comments` },
  { name: "CloseNotes", queryG: `closeNotes` },
  { name: "CommentsAndWorkNotes", queryG: `commentsAndWorkNotes` },
  { name: "ConfigurationItem ", queryG: `configurationItem {name}` },
  { name: "ContactType ", queryG: `contactType {name}` },
  { name: "Contract", queryG: `contract` },
  { name: "Correlationdisplay", queryG: `correlationdisplay` },
  { name: "CorrelationId", queryG: `correlationId` },
  { name: "Created", queryG: `created` },
  { name: "Createdby", queryG: `createdby` },
  { name: "Deliveryaddress", queryG: `deliveryaddress` },
  { name: "Deliveryplan ", queryG: `deliveryplan {name}` },
  { name: "Deliverytask", queryG: `deliverytask` },
  { name: "Description", queryG: `description` },
  { name: "Domain ", queryG: `domain {name}` },
  { name: "DomainPath", queryG: `domainPath` },
  { name: "DraftKb", queryG: `draftKb` },
  { name: "DueDate", queryG: `dueDate` },
  { name: "Duration", queryG: `duration` },
  { name: "Effectivenumber", queryG: `effectivenumber` },
  { name: "Escalation ", queryG: `escalation {status}` },
  { name: "Esignaturedocument", queryG: `esignaturedocument` },
  { name: "Esignaturetemplate", queryG: `esignaturetemplate` },
  { name: "Expectedstart", queryG: `expectedstart` },
  { name: "Fault", queryG: `fault` },
  { name: "Followup", queryG: `followup` },
  { name: "Grouplist", queryG: `grouplist` },
  { name: "Gsdreassignmentcount", queryG: `gsdreassignmentcount` },
  { name: "Id", queryG: `id` },
  { name: "Impact ", queryG: `impact {status}` },
  { name: "LastUpdated", queryG: `lastUpdated` },
  { name: "Location ", queryG: `location {name}` },
  { name: "MadeSla", queryG: `madeSla` },
  { name: "Number", queryG: `number` },
  { name: "Opened", queryG: `opened` },
  { name: "OpenedBy ", queryG: `openedBy {name}` },
  { name: "Orderr", queryG: `orderr` },
  { name: "OutOfPolicy", queryG: `outOfPolicy` },
  { name: "Owner ", queryG: `owner {name}` },
  { name: "OwnerGroup ", queryG: `ownerGroup {name}` },
  { name: "Parent", queryG: `parent` },
  { name: "Parentinteraction", queryG: `parentinteraction` },
  { name: "Price", queryG: `price` },
  { name: "Priority ", queryG: `priority {name}` },
  { name: "Reassignmentcount", queryG: `reassignmentcount` },
  { name: "RequestedFor ", queryG: `requestedFor {name}` },
  { name: "Requestedfordate", queryG: `requestedfordate` },
  { name: "RequestState ", queryG: `requestState {name}` },
  { name: "ResolveTime", queryG: `resolveTime` },
  { name: "Routereason", queryG: `routereason` },
  { name: "Service ", queryG: `service {name}` },
  { name: "Serviceoffering", queryG: `serviceoffering` },
  { name: "ServiceTower ", queryG: `serviceTower {name}` },
  { name: "ShortDescription", queryG: `shortDescription` },
  { name: "Skills", queryG: `skills` },
  { name: "Sladue ", queryG: `sladue {name}` },
  { name: "SpecialInstructions", queryG: `specialInstructions` },
  { name: "SpecifyCi", queryG: `specifyCi` },
  { name: "Stage ", queryG: `stage {name}` },
  { name: "State ", queryG: `state {name}` },
  { name: "StrikeCount", queryG: `strikeCount` },
  { name: "StrikeDate", queryG: `strikeDate` },
  { name: "Tags", queryG: `tags` },
  { name: "Tasktype ", queryG: `tasktype {name}` },
  { name: "Timeworked", queryG: `timeworked` },
  { name: "UniversalRequest", queryG: `universalRequest` },
  { name: "Updated", queryG: `updated` },
  { name: "Updatedby ", queryG: `updatedby {name}` },
  { name: "Updates", queryG: `updates` },
  { name: "UponApproval ", queryG: `uponApproval {name}` },
  { name: "Uponreject ", queryG: `uponreject {name}` },
  { name: "Urgency ", queryG: `urgency {status}` },
  { name: "Userinput", queryG: `userinput` },
  { name: "VendorCi", queryG: `vendorCi` },
  { name: "VendorContact", queryG: `vendorContact` },
  { name: "Vendorgroup ", queryG: `vendorgroup {status}` },
  { name: "VendorName", queryG: `vendorName` },
  { name: "VendorPriority ", queryG: `vendorPriority {status}` },
  { name: "VendorService", queryG: `vendorService` },
  { name: "VendorState ", queryG: `vendorState {status}` },
  { name: "Watchlist", queryG: `watchlist` },
  { name: "Worknoteslist", queryG: `worknoteslist` },
];
